from snakemake.utils import min_version
min_version('7.0')

# Include base environment and tools that are required for Snakefile script (e.g., Pandas)
conda: "envs/global_env.yaml"
# Import config file so all included scripts have access to config data
configfile: "config/config.yaml"

include: "rules/commons.smk"
include: "rules/process.smk"

rule all:
    input: 
        expand("results/subsample/{id}_sub.fastq.gz", id=samples['sample_id']),
        expand("results/minimap2/{id}_mapped.sorted.bam", id=samples['sample_id']),
        expand("results/mpileup/{id}.mpileup.tsv", id=samples['sample_id']),
        expand("results/samtools_stats/{id}.stats.txt", id=samples['sample_id']),
        expand("results/samtools_stats/{id}_indel_rate.tsv", id=samples['sample_id']),
        expand("results/read_len_hist/{id}_rl_hist.svg", id=samples['sample_id']),